# Introduction

Climate change is among the most pressing problems today. Environmental and societal effects like extreme weather events, increasing sea levels have been augmented 
due to increasing proportions of green house gases and eventually global warming. Majorly carbon dioxide (CO2) is the front runner for causing increase in the average
temperature of the earth.

This project aims to study the variations and correlations in the emissions of various greenhouse gases like Carbon Dioxide (CO2), Nitrous Oxide (N2O), Methane (CH4)
and fluorinated gases (F-gas). Moreover, this study aims to observe the patterns emissions of these gases across different countries across different sectors.Some of 
the research questions this project aims to answer are as follows:
1. What are the trends in the emission of greenhouse gases over time ?

2. Which gases contribute the most to the total emissions globally and regionally ?

3. Which sectors are responsible for contributing more amount of green house gases and how do these vary across countries?

4. Which countries are contributing to the maximum amount of green house gases ? 

5. How has the emissions of different gases evolved across the years across different countries and across different sectors ?


Understanding the contributions of different gases can guide the government and policymakers in setting regulations for certain sectors and designing new policies.
Moreover, insights into sector specific emissions can help these policymakers make policies targeted at reducing the emission of greenhouse gases. 

Identifying the emissions across various countries can allow policymakers and researchers to figure out high emission countries, promote equity in climate action, 
tailor country specific strategies at global summits and meets and many more. Monitoring the trends of emissions of these gases would also give insights about the rate of 
increase or rate of decrease of emissions over the years, which is in turn crucial for countries to track their progress towards their climate goals. 

To conclude, this project has the potential to provide valuable insights into patterns of emissions of greenhouse gases making the way for data-driven policy making.
This would allow the researchers and policymakers to design strategies to tackle climate change.

